### ISSUE TITLE
BG City Access in EET

### ISSUE THREAD

**Issue by RoxanneSHS** [Gibberlings3/CowledMenace#2]
This is more a compatibility question than an issue.
In EET the bridge to enter the city of Baldur's Gate is closed (due to the SoD events).
From BG0900.bcs
IF
	Global("K#Drawbridge","BG0900",0)
	GlobalGT("Chapter","GLOBAL",7)
THEN
	RESPONSE #100
		SetGlobal("K#Drawbridge","BG0900",1)
		OpenDoor("DoorDraw")
END
Consequently the city maps are not accessible on the worldmap after SoD until you lower the bridge again.

In one of my own mods I have a plot event that opens the city again. I just wonder how you do it in your mod. if at all?

**Comment by Maltodaxtrin** [comment]
hey Roxanne,

Damn, did way too much of my testing in BG1 before SoD.

Is re-opening the Door simply just a matter of setting "K#Drawbridge" to 0 again and closing the door draw? How did you do it?

**Comment by RoxanneSHS** [comment]
Setting it to 0 would just create a loop.
I used this 
IF
	Global("SanSoDSkie","Global",6)
THEN
	RESPONSE #100
		SetGlobal("SanSoDSkie","Global",7)
		SetGlobal("K#Drawbridge","BG0900",2)
		CloseDoor("DoorDraw")
END

"SanSoDSkie" is the global used in my quest where you clear your name from being Skie's murderer, which is the reason why k4thos closed the town in EET. You are an escaped criminal until you somehow prove innocent - or maybe are needed again by the Dukes. K4thos left this open to modders to open the town by their own story.

So however you decide to solve it, that last
SetGlobal("K#Drawbridge","BG0900",2)
CloseDoor("DoorDraw")
is what does it. Still, the player afterwards needs to enter the town like on the first visit and re-explore the other city areas to put them back on the map.

**Comment by Maltodaxtrin** [comment]
Thank you Roxanne, much appreciated!

As my quest can still be completed even if you never return to Baldur's Gate, the mod is technically "functional", but yeah, quite a shame. I will start working on a fix! I have an idea already :)

**Comment by RoxanneSHS** [comment]
Just for compatibility - in my mod you get the dagger with Skie's soul from Bodhi's messenger Valen and you can free her with some temple help. Skie then returns back to BG and thus your innocence is proven. So probably you come up with something different.

**Comment by Maltodaxtrin** [comment]
Do you have a variable that tracks this progress? Because in my mod what I could do is

if !Global("yourVariable","GLOBAL",1)
THEN
do my stuff that gives entry to BG back

so that if you already proved your innocence with your mod then I don't need to do anything.

edit: oh wait, better yet... I'll just check if any other mod already gave you access back by checking if 

!Global("K#Drawbridge","BG0900",1)
or
Global("K#Drawbridge","BG0900",2)

**Comment by RoxanneSHS** [comment]
The thing with checking the K#Drawbridge global is that it is local to are BG0900 (Wyrm's Crossing) so you cannot evaluate it elsewhere. So if you want your stuff to trigger elsewhere, it will not do.

For my mod you can check GlobalGT("SanSoDSkie","Global",6) in which case the bridge will be down once more even if my story has advanced further.

For other mods I have no idea - fact is that until now mine was the only mod I know of that had content for BG1 (town) areas in EET after the transition. (My other EET mods like e.g Caelar revisit the BG1 world but do not enter the city itself).

Anyway, the easiest thing would be that you just implement your idea to make sure the city is open for your plot and if another mod already did it, why bother? This is like in other cases where some area may be revealed on the worldmap by numerous quests, each one taking care for its own needs. It does not hurt to do it twice, it has no effect that the player will notice. (As you can see from my code, I have not included a check for the bridge status for just that reason - if it is already open, I will not get stuck.)

**Comment by Maltodaxtrin** [comment]
Well the dialog might be affected (why would you tell an NPC that BG is closed-off to you if it isn't?)

But you're right. I'll work something out!

**Comment by davideOXC** [comment]
Why do you made an other way to enteri nto the closed city, such as by a new tunnel to the sewer ?

**Comment by Maltodaxtrin** [comment]
It's an interesting idea, noted, thanks!

**Comment by Maltodaxtrin** [comment]
New version (0.2 beta) includes a fix for this :)
